import * as fs from 'fs';
import * as path from 'path';
import { DeviceInfo, Mspm0ProjectFile, ProbeType, ToolPaths } from '../model/types';
import { ensureDir, writeJsonFile, writeTextFile } from '../util/fsUtil';
import { toBackslash, toForward } from '../util/pathUtil';

export class ConfigGenerator {
	async generate(
		projectRoot: string,
		project: Mspm0ProjectFile,
		tools: ToolPaths,
		device: DeviceInfo,
		extensionPath?: string
	): Promise<void> {
		const vscodeDir = path.join(projectRoot, '.vscode');
		ensureDir(vscodeDir);

		const gcc = toForward(tools.gcc);
		const sdk = toForward(tools.sdk);
		const sys = toForward(tools.sysconfig);
		const jl = toForward(tools.jlink);
		const make = toForward(tools.make);
		const ocd = toForward(tools.openocd || '');

		const gccBin = `${gcc}/bin`;
		const taskPath = [toBackslash(make), toBackslash(gccBin), toBackslash(sys), toBackslash(jl), toBackslash(ocd), '${env:Path}'].join(';');
		const flashPath = [toBackslash(make), toBackslash(gccBin), toBackslash(jl), toBackslash(ocd), '${env:Path}'].join(';');
		const sysPath = [toBackslash(sys), toBackslash(make), '${env:Path}'].join(';');
		const cleanPath = [toBackslash(make), '${env:Path}'].join(';');
		const termPath = [toBackslash(make), toBackslash(gccBin), toBackslash(sys), toBackslash(jl), toBackslash(ocd), '${env:Path}'].join(';');
		const svd = this.resolveSvd(device.svd);

		writeTextFile(
			path.join(projectRoot, 'toolpaths.mk'),
			[
				'# Generated by MSPM0 Toolkit - do not edit by hand if using the extension',
				`GCC_PATH=${gcc}`,
				`SDK=${sdk}`,
				`SYSCONFIG_ROOT=${sys}`,
				`JLINK_ROOT=${jl}`,
				`MAKE_BIN=${make}`,
				`OPENOCD_BIN=${ocd}`,
				'',
			].join('\n')
		);

		this.writeJsonMerged(
			path.join(vscodeDir, 'settings.json'),
			{
				'files.associations': { '*.h': 'c', '*.c': 'c' },
				'cortex-debug.armToolchainPath': gccBin,
				'cortex-debug.gdbPath': `${gccBin}/arm-none-eabi-gdb.exe`,
				'cortex-debug.JLinkGDBServerPath': `${jl}/JLinkGDBServerCL.exe`,
				'cortex-debug.openocdPath': ocd ? `${ocd}/openocd.exe` : '',
				'terminal.integrated.env.windows': { Path: termPath },
			},
			(existing, gen) => ({
				...existing,
				...gen,
				'files.associations': {
					...(existing['files.associations'] || {}),
					...(gen['files.associations'] || {}),
				},
				'terminal.integrated.env.windows': {
					...(existing['terminal.integrated.env.windows'] || {}),
					...(gen['terminal.integrated.env.windows'] || {}),
				},
			})
		);

		this.writeJsonMerged(
			path.join(vscodeDir, 'c_cpp_properties.json'),
			{
				configurations: [
					{
						name: project.device,
						includePath: [
							'${workspaceFolder}/**',
							'${workspaceFolder}/src',
							'${workspaceFolder}/syscfg',
							`${sdk}/source`,
							`${sdk}/source/third_party/CMSIS/Core/Include`,
							`${gcc}/arm-none-eabi/include`,
						],
						defines: [device.deviceDefine, device.familyDefine],
						compilerPath: `${gccBin}/arm-none-eabi-gcc.exe`,
						cStandard: 'c99',
						intelliSenseMode: 'gcc-arm',
					},
				],
				version: 4,
			},
			(existing, gen) => {
				const configs = Array.isArray(existing.configurations) ? [...existing.configurations] : [];
				const next = gen.configurations[0];
				const idx = configs.findIndex((c: { name?: string }) => c?.name === next.name);
				if (idx >= 0) {
					configs[idx] = next;
				} else {
					configs.push(next);
				}
				return { ...existing, configurations: configs, version: gen.version };
			}
		);

		const launchConfigs = this.buildLaunchConfigs(project, device, tools, svd, gccBin, jl, ocd);

		this.writeJsonMerged(
			path.join(vscodeDir, 'launch.json'),
			{
				version: '0.2.0',
				configurations: launchConfigs,
			},
			(existing, gen) => {
				const configs = Array.isArray(existing.configurations) ? [...existing.configurations] : [];
				for (const next of gen.configurations) {
					const idx = configs.findIndex((c: { name?: string }) => c?.name === next.name);
					if (idx >= 0) {
						configs[idx] = next;
					} else {
						configs.push(next);
					}
				}
				return { ...existing, version: gen.version, configurations: configs };
			}
		);

		this.writeJsonMerged(
			path.join(vscodeDir, 'tasks.json'),
			{
				version: '2.0.0',
				tasks: [
					{
						label: 'build',
						type: 'shell',
						command: 'make',
						args: ['-j8'],
						options: { cwd: '${workspaceFolder}', env: { Path: taskPath } },
						group: { kind: 'build', isDefault: true },
						problemMatcher: ['$gcc'],
					},
					{
						label: 'clean',
						type: 'shell',
						command: 'make',
						args: ['clean'],
						options: { cwd: '${workspaceFolder}', env: { Path: cleanPath } },
						problemMatcher: [],
					},
					{
						label: 'syscfg',
						type: 'shell',
						command: 'make',
						args: ['syscfg'],
						options: { cwd: '${workspaceFolder}', env: { Path: sysPath } },
						problemMatcher: [],
					},
					{
						label: 'syscfg-gui',
						type: 'shell',
						command: toBackslash(`${sys}/sysconfig_gui.bat`),
						args: [
							'--product',
							`${sdk}/.metadata/product.json`,
							'--compiler',
							'gcc',
							'--output',
							'${workspaceFolder}/syscfg',
							'${workspaceFolder}/' + project.syscfgFile,
						],
						options: { cwd: '${workspaceFolder}' },
						problemMatcher: [],
						presentation: { reveal: 'silent', panel: 'shared' },
					},
					{
						label: 'flash',
						type: 'shell',
						command: 'make',
						args: ['flash'],
						options: { cwd: '${workspaceFolder}', env: { Path: flashPath } },
						problemMatcher: [],
						dependsOn: ['build'],
					},
				],
			},
			(existing, gen) => {
				const tasks = Array.isArray(existing.tasks) ? [...existing.tasks] : [];
				for (const next of gen.tasks) {
					const idx = tasks.findIndex((c: { label?: string }) => c?.label === next.label);
					if (idx >= 0) {
						tasks[idx] = next;
					} else {
						tasks.push(next);
					}
				}
				return { ...existing, version: gen.version, tasks };
			}
		);

		this.writeJsonMerged(
			path.join(vscodeDir, 'extensions.json'),
			{
				recommendations: [
					'ms-vscode.cpptools',
					'ms-vscode.cpptools-extension-pack',
					'marus25.cortex-debug',
					'ti-development-tools.cortex-debug-dp-mspm0',
					'ms-vscode.vscode-serial-monitor',
					'ms-vscode.hexeditor',
					'dan-c-underwood.arm',
				],
			},
			(existing, gen) => {
				const rec = new Set([
					...(Array.isArray(existing.recommendations) ? existing.recommendations : []),
					...gen.recommendations,
				]);
				return { ...existing, recommendations: Array.from(rec) };
			}
		);

		writeTextFile(
			path.join(vscodeDir, 'flash.jlink'),
			['r', 'h', `loadfile ${project.executable}`, 'r', 'g', 'qc', ''].join('\n')
		);

		this.writeOpenocdConfig(vscodeDir, project, extensionPath);
	}

	private buildLaunchConfigs(
		project: Mspm0ProjectFile,
		device: DeviceInfo,
		_tools: ToolPaths,
		svd: string,
		gccBin: string,
		jl: string,
		ocd: string
	): Array<Record<string, unknown>> {
		const exe = '${workspaceFolder}/' + project.executable;
		const configs: Array<Record<string, unknown>> = [
			{
				name: 'Debug (J-Link)',
				cwd: '${workspaceFolder}',
				executable: exe,
				request: 'launch',
				type: 'cortex-debug',
				runToEntryPoint: 'main',
				servertype: 'jlink',
				device: device.jlinkDevice,
				interface: project.interface,
				serverpath: `${jl}/JLinkGDBServerCL.exe`,
				gdbPath: `${gccBin}/arm-none-eabi-gdb.exe`,
				armToolchainPath: gccBin,
				svdFile: svd,
				preLaunchTask: 'build',
			},
			{
				name: 'Attach (J-Link)',
				cwd: '${workspaceFolder}',
				executable: exe,
				request: 'attach',
				type: 'cortex-debug',
				servertype: 'jlink',
				device: device.jlinkDevice,
				interface: project.interface,
				serverpath: `${jl}/JLinkGDBServerCL.exe`,
				gdbPath: `${gccBin}/arm-none-eabi-gdb.exe`,
				armToolchainPath: gccBin,
				svdFile: svd,
			},
		];

		const openocdProbes: ProbeType[] = ['openocd', 'xds110', 'cmsis-dap'];
		for (const probe of openocdProbes) {
			const label = probe === 'openocd' ? 'OpenOCD' : probe === 'xds110' ? 'XDS110' : 'CMSIS-DAP';
			configs.push({
				name: `Debug (${label})`,
				cwd: '${workspaceFolder}',
				executable: exe,
				request: 'launch',
				type: 'cortex-debug',
				runToEntryPoint: 'main',
				servertype: 'openocd',
				configFiles: ['.vscode/openocd.cfg'],
				searchDir: ['.vscode'],
				openOCDLaunchCommands: [`adapter speed ${project.speed || 4000}`],
				gdbPath: `${gccBin}/arm-none-eabi-gdb.exe`,
				armToolchainPath: gccBin,
				serverpath: ocd ? `${ocd}/openocd.exe` : undefined,
				svdFile: svd,
				preLaunchTask: 'build',
			});
			configs.push({
				name: `Attach (${label})`,
				cwd: '${workspaceFolder}',
				executable: exe,
				request: 'attach',
				type: 'cortex-debug',
				servertype: 'openocd',
				configFiles: ['.vscode/openocd.cfg'],
				searchDir: ['.vscode'],
				gdbPath: `${gccBin}/arm-none-eabi-gdb.exe`,
				armToolchainPath: gccBin,
				serverpath: ocd ? `${ocd}/openocd.exe` : undefined,
				svdFile: svd,
			});
		}

		return configs;
	}

	private writeOpenocdConfig(vscodeDir: string, project: Mspm0ProjectFile, extensionPath?: string): void {
		const speed = project.speed || 4000;
		const iface = (project.interface || 'swd').toLowerCase();
		let interfaceScript = 'interface/jlink.cfg';
		if (project.probe === 'xds110') {
			interfaceScript = 'interface/xds110.cfg';
		} else if (project.probe === 'cmsis-dap') {
			interfaceScript = 'interface/cmsis-dap.cfg';
		} else if (project.probe === 'openocd') {
			// generic openocd defaults to cmsis-dap unless user edits
			interfaceScript = 'interface/cmsis-dap.cfg';
		} else if (project.probe === 'jlink') {
			interfaceScript = 'interface/jlink.cfg';
		}

		// Prefer bundled resources if present (for offline/custom), but OpenOCD still needs scripts in its share tree.
		// Generate a self-contained cfg that uses OpenOCD's find path.
		const lines = [
			`# Generated by MSPM0 Toolkit for probe=${project.probe}`,
			`source [find ${interfaceScript}]`,
			`transport select ${iface}`,
			`adapter speed ${speed}`,
			'',
			'# MSPM0 Cortex-M0+ SWD target',
			'source [find target/swj-dp.tcl]',
			'set _CHIPNAME mspm0',
			'swj_newdap $_CHIPNAME cpu -expected-id 0x0bc11477 -irlen 4',
			'dap create $_CHIPNAME.dap -chain-position $_CHIPNAME.cpu',
			'target create $_CHIPNAME.cpu cortex_m -dap $_CHIPNAME.dap',
			'$_CHIPNAME.cpu configure -work-area-phys 0x20200000 -work-area-size 0x2000 -work-area-backup 0',
			'',
		];

		// Optional: copy resource snippets next to cfg for reference
		if (extensionPath) {
			const resDir = path.join(extensionPath, 'resources', 'openocd');
			if (fs.existsSync(resDir)) {
				for (const f of fs.readdirSync(resDir)) {
					const src = path.join(resDir, f);
					const dst = path.join(vscodeDir, f);
					try {
						fs.copyFileSync(src, dst);
					} catch {
						// ignore
					}
				}
			}
		}

		writeTextFile(path.join(vscodeDir, 'openocd.cfg'), lines.join('\n'));
	}

	private readJsonIfExists(filePath: string): Record<string, unknown> | undefined {
		try {
			if (!fs.existsSync(filePath)) {
				return undefined;
			}
			return JSON.parse(fs.readFileSync(filePath, 'utf8')) as Record<string, unknown>;
		} catch {
			return undefined;
		}
	}

	private writeJsonMerged(
		filePath: string,
		generated: Record<string, unknown>,
		merge: (existing: any, gen: any) => Record<string, unknown>
	): void {
		const existing = this.readJsonIfExists(filePath);
		const data = existing ? merge(existing, generated) : generated;
		writeJsonFile(filePath, data);
	}

	private resolveSvd(svdName: string): string {
		const extRoot = path.join(process.env.USERPROFILE || process.env.HOME || '', '.vscode', 'extensions');
		try {
			if (!fs.existsSync(extRoot)) {
				return '';
			}
			const hits = fs
				.readdirSync(extRoot, { withFileTypes: true })
				.filter((d) => d.isDirectory() && d.name.startsWith('ti-development-tools.cortex-debug-dp-mspm0'))
				.map((d) => path.join(extRoot, d.name, 'data', svdName))
				.filter((p) => fs.existsSync(p))
				.sort()
				.reverse();
			return hits[0] ? toForward(hits[0]) : '';
		} catch {
			return '';
		}
	}
}
